# Generated by Django 2.0 on 2017-12-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Chuus',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Sawal',
        ),
    ]
